// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBWaIbrQILZ4LSgEvpgVRRAQQDzAXICndk',
    appId: '1:773723790875:web:e42d093c2ec54034d622be',
    messagingSenderId: '773723790875',
    projectId: 'lolche-wiki',
    authDomain: 'lolche-wiki.firebaseapp.com',
    storageBucket: 'lolche-wiki.appspot.com',
    measurementId: 'G-8RVCXFF8SP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6xjKtlpj3aRnuzrgAU6IdULT0v5xLlgE',
    appId: '1:773723790875:android:3d69dead9645feafd622be',
    messagingSenderId: '773723790875',
    projectId: 'lolche-wiki',
    storageBucket: 'lolche-wiki.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAfxwiPXXg6qgI4K-o0BEVYDiqh5sf4UFE',
    appId: '1:773723790875:ios:6518d2037cd4c11ed622be',
    messagingSenderId: '773723790875',
    projectId: 'lolche-wiki',
    storageBucket: 'lolche-wiki.appspot.com',
    iosBundleId: 'com.lnk.lolche.app',
  );
}
